##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Sun Aug 23 10:20:26 MSK 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = 01-BLE_Test


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/adc.c \
Core/Src/dma.c \
Core/Src/ipcc.c \
Core/Src/rf.c \
Core/Src/rtc.c \
Core/Src/app_entry.c \
Core/Src/app_debug.c \
Core/Src/hw_timerserver.c \
Core/Src/hw_uart.c \
Core/Src/stm32_lpm_if.c \
Core/Src/stm32wbxx_it.c \
Core/Src/stm32wbxx_hal_msp.c \
USB_Device/Target/usbd_conf.c \
USB_Device/App/usb_device.c \
USB_Device/App/usbd_desc.c \
USB_Device/App/usbd_cdc_if.c \
STM32_WPAN/App/app_ble.c \
STM32_WPAN/App/p2p_server_app.c \
STM32_WPAN/Target/hw_ipcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pcd_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_usb.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_rcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rcc_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_flash_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_gpio.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_hsem.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_dma_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_pwr_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_cortex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_exti.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_adc_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_ll_adc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_ipcc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_rtc_ex.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim.c \
Drivers/STM32WBxx_HAL_Driver/Src/stm32wbxx_hal_tim_ex.c \
Core/Src/system_stm32wbxx.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci/shci.c \
Middlewares/ST/STM32_WPAN/utilities/dbg_trace.c \
Middlewares/ST/STM32_WPAN/utilities/otp.c \
Middlewares/ST/STM32_WPAN/utilities/stm_list.c \
Middlewares/ST/STM32_WPAN/utilities/stm_queue.c \
Middlewares/ST/STM32_WPAN/ble/core/template/osal.c \
Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gap_aci.c \
Middlewares/ST/STM32_WPAN/ble/core/auto/ble_gatt_aci.c \
Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hal_aci.c \
Middlewares/ST/STM32_WPAN/ble/core/auto/ble_hci_le.c \
Middlewares/ST/STM32_WPAN/ble/core/auto/ble_l2cap_aci.c \
Middlewares/ST/STM32_WPAN/ble/svc/Src/p2p_stm.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.c \
Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.c \
Middlewares/ST/STM32_WPAN/ble/svc/Src/svc_ctl.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
Utilities/lpm/tiny_lpm/stm32_lpm.c \
Utilities/sequencer/stm32_seq.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c

# ASM sources
ASM_SOURCES =  \
startup_stm32wb55xx_cm4.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32WB55xx


# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-ISTM32_WPAN/App \
-IUSB_Device/App \
-IUSB_Device/Target \
-IDrivers/STM32WBxx_HAL_Driver/Inc \
-IDrivers/STM32WBxx_HAL_Driver/Inc/Legacy \
-IUtilities/lpm/tiny_lpm \
-IMiddlewares/ST/STM32_WPAN \
-IMiddlewares/ST/STM32_WPAN/interface/patterns/ble_thread \
-IMiddlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl \
-IMiddlewares/ST/STM32_WPAN/interface/patterns/ble_thread/shci \
-IMiddlewares/ST/STM32_WPAN/utilities \
-IMiddlewares/ST/STM32_WPAN/ble/core \
-IMiddlewares/ST/STM32_WPAN/ble/core/auto \
-IMiddlewares/ST/STM32_WPAN/ble/core/template \
-IMiddlewares/ST/STM32_WPAN/ble/svc/Inc \
-IMiddlewares/ST/STM32_WPAN/ble/svc/Src \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-IDrivers/CMSIS/Device/ST/STM32WBxx/Include \
-IUtilities/sequencer \
-IMiddlewares/ST/STM32_WPAN/ble \
-IDrivers/CMSIS/Include


# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = stm32wb55xx_flash_cm4.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
